version: 2.0
jobs:
 build:
   docker:
     - image: alpine:3.7
   steps:
     - setup_remote_docker
     - run:
         name: Start docker
         command: |
<<<<<<< HEAD
          docker-compose build
=======
          mkdir -p ./volumes/app/mattermost/{data,logs,config,plugins}
          sudo chown -R 2000:2000 ./volumes/app/mattermost/
>>>>>>> 6cd1e86... test
          docker-compose up
     - run:
         name: Tests
         command: |
           cd node
           npm run test