version: 2.0
jobs:
 build:
   docker:
     - image: alpine:3.7
   steps:
     - setup_remote_docker
     - run:
         name: Start docker
         command: |
          docker-compose build
          docker-compose up
     - run:
         name: Tests
         command: |
           cd node
           npm run test